name: 'Profile Readme Development Stats'
author: Chloe Chi
description: 'Are you an early bird or a night owl? When are you most productive during the day? Let''s check out in your readme!'

on:
  schedule:
    # Runs at 2:30 PDT
    - cron: '40 14 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: ChloeChii/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}